### ISSUE TITLE
Personal Work on Dyeable Ender Chests

### ISSUE THREAD

**Issue by ghost** [tryashtar/datapacks#13]

**Comment by tryashtar** [comment]
Just seeing this now for the first time. Thanks so much!

**Comment by Shyclops** [comment]
@alexis-evelyn I've recently started looking at/using this data pack and would love to get it working in the nether and end, as well as clean it up a bit, however i'm quite new to datapacks. If you could provide some additional details on how I might go about implementing the nether, the end, as well as the other points that you mentioned in your comment

Thanks for your time

**Comment by alexis-evelyn** [comment]
I haven't played Minecraft in ages now. So, I do not remember anything about what I did now. Sorry about that.
