### ISSUE TITLE
Dyeable Ender Chests and Extended Pistons bug.

### ISSUE THREAD

**Issue by EnderHater** [tryashtar/datapacks#6]
**Dyeable Ender Chests:**

When you break the minecart ontop of the station, the dye combination inside glitches out, and the minecart wont summon itself, even after a complete game/world restart and after /reload.

**Extended Pistons:**

They act like normal dispensers when placed, even though the command block is summoned when placing them.

**Comment by tryashtar** [comment]
Thanks for the report.
Is there any way to break the minecart in survival? I specifically made it `Invulnerable`. If you're breaking it in creative, there's not much reason to fix this, though I might change my mind.

As for extended pistons, dispensing things is unfixable. Although are they dispensing your upgrades? That should not happen. If it's doing that, could you upload a screenshot of the setup making that happen? Thanks again.

**Comment by EnderHater** [comment]
@tryashtar The piston only dispenses the pistons that are in it, but I haven't tested the upgrades part of it.

**Comment by tryashtar** [comment]
As in, the pistons you used to make it longer? Could you upload a screenshot?

**Comment by EnderHater** [comment]
Yes. I'm using normal pistons, and the extended piston block just acts like a normal dispenser.

Both sticky and normal.

(I would call myself EnderSlime but GitHub is being stupid so Im stuck with EnderHater :P)

**Comment by Testsr** [comment]
Extended piston do not work below level 5.

**Comment by Testsr** [comment]
The fill command bounds can be negative.

**Comment by Testsr** [comment]
The piston is place in slot-1
